### ISSUE TITLE
Configuration option for quote character

### ISSUE THREAD

**Issue by ticktricktrack** [joseramonc/rails-partials#13]
I always turn `render 'my_partial'` into `render "my_partial"`

Any chance that can be made configurable?

**Comment by joseramonc** [comment]
Yes, It can be configurable, regardless, the default between `'` or `"` could be changed meanwhile. I have no personal favorite, so changing `'` for `"` is ok with me.

I'm not sure when I'm going to be able to look into this. If you can help me ship any of this features It would be appreciated.
